export const gnbData = ['샌드위치', '랩 기타', '샐러드', '아침메뉴', '스마일 썹', '단체메뉴'];
export const menuData = {
  sandwich: [
    {
      krName: '로스트 치킨',
      enName: 'Roasted Chicken',
      description: '오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미',
      imageUrl: 'https://www.subway.co.kr/upload/menu/Roasted-Chicken_20211231095032718.png',
      price: 10000,
    },
    {
      krName: '스파이시 쉬림프',
      enName: 'Spicy Shrimp',
      description: '이국적인 매콤함이 더해진 시즌 한정 스파이시 쉬림프!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%8A%A4%ED%8C%8C%EC%9D%B4%EC%8B%9C%EC%89%AC%EB%A6%BC%ED%94%84_20220615022830714.png',
      price: 10000,
    },
    {
      krName: '스파이시 쉬림프 아보카도',
      enName: 'Spicy Shrimp Avocado',
      description: '오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%8A%A4%ED%8C%8C%EC%9D%B4%EC%8B%9C%EC%89%AC%EB%A6%BC%ED%94%84%EC%95%84%EB%B3%B4%EC%B9%B4%EB%8F%84_20220615022849892.png',
      price: 10000,
    },
    {
      krName: '에그마요',
      enName: 'Egg Mayo',
      description: '오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미',
      imageUrl: 'https://www.subway.co.kr/upload/menu/Egg-Mayo_20211231094817112.png',
      price: 10000,
    },
    {
      krName: '이탈리안 비엠티',
      enName: 'Italian B.M.T.™',
      description: '오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미',
      imageUrl: 'https://www.subway.co.kr/upload/menu/Italian_B.M.T_20211231094910899.png',
      price: 10000,
    },
  ],
  wrap: [
    {
      krName: '스테이크 & 치즈 아보카도 그릴드 랩',
      enName: 'Steak & Cheese Avocado Grilled Wrap',
      description: '육즙이 쫙~ 비프 스테이크와 아보카도가 만나다!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/steak_n_cheese_avocado_grilled_wrap_20210315110316292.png',
      price: 10000,
    },
    {
      krName: '쉬림프 에그마요 랩',
      enName: 'Shrimp Egg Mayo Wrap',
      description: '부드럽고 고소한 에그마요 안에 탱글한 통새우가 푹~! 최상의 야채와 소스 조합으로 탄생한 쉬림프 에그마요 랩!!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/shrimp_egg_mayo_wrap_20210315105650669.jpg',
      price: 10000,
    },
    {
      krName: '쉬림프 에그 그릴드 랩',
      enName: 'Shrimp Egg Grilled Wrap',
      description: '더 뜨겁게, 더 맛있게 즐기자! 탱글한 새우와 부드러운 오믈렛의 만남',
      imageUrl: 'https://www.subway.co.kr/upload/menu/shrimp_egg_grilled_wrap_20210315110327118.png',
      price: 10000,
    },
    {
      krName: '치킨 베이컨 미니 그릴드 랩',
      enName: 'Chicken Bacon Mini Grilled Wrap',
      description: '더 뜨겁게 더 맛있게 즐기자! 담백한 치킨, 바삭한 베이컨 비츠가 쏙',
      imageUrl: 'https://www.subway.co.kr/upload/menu/chicken_bacon_mini_grilled_wrap_20210315110305393.png',
      price: 10000,
    },
    {
      krName: '스테이크 & 치즈 아보카도 랩',
      enName: 'Steak & Cheese Avocado Wrap',
      description: '육즙 가득 스테이크에 프레쉬함을 더해줄아보카도와 슈레드치즈 그리고모차렐라치즈까지!최상의 야채와 소스 조합으로 탄생한스테이크 & 치즈 아보카도 랩!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/steak_n_cheese_avocado_wrap_20210315105638140.jpg',
      price: 10000,
    },
  ],
  salad: [
    {
      krName: '스파이시 쉬림프',
      enName: 'Spicy Shrimp',
      description: '빨간맛에 빠진 쉬림프! 이국적인 매콤함이 더해진 시즌 한정 스파이시 쉬림프!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%8A%A4%ED%8C%8C%EC%9D%B4%EC%8B%9C_20220712101947424.png',
      price: 10000,
    },
    {
      krName: '스파이시 쉬림프 아보카도',
      enName: 'Spicy Shrimp Avocado',
      description: '매콤한 쉬림프와 부~드러운 아보카도가 만나, 이국적인 풍미 업!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%95%84%EB%B3%B4%EC%B9%B4%EB%8F%84_20220712101835725.png',
      price: 10000,
    },
    {
      krName: '쉬림프',
      enName: 'Shrimp',
      description: '빨간맛에 빠진 쉬림프! 이국적인 매콤함이 더해진 시즌 한정 스파이시 쉬림프!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%89%AC%EB%A6%BC%ED%94%84_20220413025617416.png',
      price: 10000,
    },
    {
      krName: 'K-바비큐',
      enName: 'K-BBQ',
      description: '써브웨이 최초의 코리안 스타일 샐러드! 마늘, 간장 그리고 은은한 불맛까지!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/K-%EB%B0%94%EB%B9%84%ED%81%90-%EC%83%90%EB%9F%AC%EB%93%9C-%EB%8B%A8%ED%92%88_20220413025007802.png',
      price: 10000,
    },
    {
      krName: '로티세리 바비큐 치킨',
      enName: 'Rotisserie Barbecue Chicken',
      description: '촉촉한 바비큐 치킨의 풍미가득. 손으로 찢어 더욱 부드러운 치킨이 샐러드에 쏙!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EB%A1%9C%ED%8B%B0%EC%84%B8%EB%A6%AC_20220413025601652.png',
      price: 10000,
    },
  ],
  breakfast: [
    {
      krName: '스테이크, 에그 & 치즈',
      enName: 'Steak, Egg & Cheese',
      description: '육즙 가득 비프 스테이크로 든든한 아침 식사',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%8A%A4%ED%85%8C%EC%9D%B4%ED%81%AC,%20%EC%97%90%EA%B7%B8%20&%20%EC%B9%98%EC%A6%88%20%EB%8B%A8%ED%92%88_20220407064223758.png',
      price: 10000,
    },
    {
      krName: '햄, 에그&치즈',
      enName: 'Ham, Egg & Cheese',
      description: '푹신한 오믈렛과 햄의 가장 클래식한 조화',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%ED%96%84,%20%EC%97%90%EA%B7%B8&%EC%B9%98%EC%A6%88%20%EB%8B%A8%ED%92%88_20220407064307837.png',
      price: 10000,
    },
    {
      krName: '쉬림프 에그 그릴드 랩',
      enName: 'Shrimp Egg Grilled Wrap',
      description: '더 뜨겁게, 더 맛있게 즐기자! 탱글한 새우와 부드러운 오믈렛의 만남',
      imageUrl: 'https://www.subway.co.kr/upload/menu/shrimp_egg_grilled_wrap_20210315110327118.png',
      price: 10000,
    },
    {
      krName: '치킨 베이컨 미니 그릴드 랩',
      enName: 'Chicken Bacon Mini Grilled Wrap',
      description: '더 뜨겁게 더 맛있게 즐기자! 담백한 치킨, 바삭한 베이컨 비츠가 쏙',
      imageUrl: 'https://www.subway.co.kr/upload/menu/chicken_bacon_mini_grilled_wrap_20210315110305393.png',
      price: 10000,
    },
    {
      krName: '스테이크 & 치즈 아보카도 랩',
      enName: 'Steak & Cheese Avocado Wrap',
      description: '육즙 가득 스테이크에 프레쉬함을 더해줄아보카도와 슈레드치즈 그리고모차렐라치즈까지!최상의 야채와 소스 조합으로 탄생한스테이크 & 치즈 아보카도 랩!',
      imageUrl: 'https://www.subway.co.kr/upload/menu/steak_n_cheese_avocado_wrap_20210315105638140.jpg',
      price: 10000,
    },
  ],
  'smlie sub': [
    {
      krName: '머쉬룸 수프',
      enName: 'Mushroom Soup',
      description: '2020년 겨울, 새롭게 선보이는 부드러운 머쉬룸 수프',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EB%A8%B8%EC%89%AC%EB%A3%B8_20220412043748530.png',
      price: 10000,
    },
    {
      krName: '스파이시 쉬림프 아보카도',
      enName: 'Spicy Shrimp Avocado',
      description: '오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%8A%A4%ED%8C%8C%EC%9D%B4%EC%8B%9C%EC%89%AC%EB%A6%BC%ED%94%84%EC%95%84%EB%B3%B4%EC%B9%B4%EB%8F%84_20220615022849892.png',
      price: 10000,
    },
    {
      krName: '에그마요',
      enName: 'Egg Mayo',
      description: '오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미',
      imageUrl: 'https://www.subway.co.kr/upload/menu/Egg-Mayo_20211231094817112.png',
      price: 10000,
    },
    {
      krName: '이탈리안 비엠티',
      enName: 'Italian B.M.T.™',
      description: '오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미',
      imageUrl: 'https://www.subway.co.kr/upload/menu/Italian_B.M.T_20211231094910899.png',
      price: 10000,
    },
    {
      krName: '스테이크, 에그 & 치즈',
      enName: 'Steak, Egg & Cheese',
      description: '육즙 가득 비프 스테이크로 든든한 아침 식사',
      imageUrl: 'https://www.subway.co.kr/upload/menu/%EC%8A%A4%ED%85%8C%EC%9D%B4%ED%81%AC,%20%EC%97%90%EA%B7%B8%20&%20%EC%B9%98%EC%A6%88%20%EB%8B%A8%ED%92%88_20220407064223758.png',
      price: 10000,
    },
  ],
  group: [
    {
      krName: '프레쉬 파티플래터',
      enName: 'Fresh Party Platter',
      description: '터키, 햄, 참치, 에그마요, 클럽으로 구성된 어디서든 신선하게 즐길 수 있는 파티플래터',
      imageUrl: 'https://www.subway.co.kr/upload/menu/fresh_party_platter_20210315013350015.jpg',
      price: 10000,
    },
    {
      krName: '프레쉬 파티플래터',
      enName: 'Fresh Party Platter',
      description: '터키, 햄, 참치, 에그마요, 클럽으로 구성된 어디서든 신선하게 즐길 수 있는 파티플래터',
      imageUrl: 'https://www.subway.co.kr/upload/menu/fresh_party_platter_20210315013350015.jpg',
      price: 10000,
    },
    {
      krName: '프레쉬 파티플래터',
      enName: 'Fresh Party Platter',
      description: '터키, 햄, 참치, 에그마요, 클럽으로 구성된 어디서든 신선하게 즐길 수 있는 파티플래터',
      imageUrl: 'https://www.subway.co.kr/upload/menu/fresh_party_platter_20210315013350015.jpg',
      price: 10000,
    },
    {
      krName: '프레쉬 파티플래터',
      enName: 'Fresh Party Platter',
      description: '터키, 햄, 참치, 에그마요, 클럽으로 구성된 어디서든 신선하게 즐길 수 있는 파티플래터',
      imageUrl: 'https://www.subway.co.kr/upload/menu/fresh_party_platter_20210315013350015.jpg',
      price: 10000,
    },
    {
      krName: '프레쉬 파티플래터',
      enName: 'Fresh Party Platter',
      description: '터키, 햄, 참치, 에그마요, 클럽으로 구성된 어디서든 신선하게 즐길 수 있는 파티플래터',
      imageUrl: 'https://www.subway.co.kr/upload/menu/fresh_party_platter_20210315013350015.jpg',
      price: 10000,
    },
  ],
};
export const vegData = [
  { name: '양상추', url: 'https://www.subway.co.kr/images/menu/img_recipe_v01.jpg' },
  { name: '토마토', url: 'https://www.subway.co.kr/images/menu/img_recipe_v02.jpg' },
  { name: '오이', url: 'https://www.subway.co.kr/images/menu/img_recipe_v03.jpg' },
  { name: '피망', url: 'https://www.subway.co.kr/images/menu/img_recipe_v04.jpg' },
  { name: '양파', url: 'https://www.subway.co.kr/images/menu/img_recipe_v05.jpg' },
  { name: '피클', url: 'https://www.subway.co.kr/images/menu/img_recipe_v06.jpg' },
  { name: '올리브', url: 'https://www.subway.co.kr/images/menu/img_recipe_v07.jpg' },
  { name: '할라피뇨', url: 'https://www.subway.co.kr/images/menu/img_recipe_v08.jpg' },
  { name: '아보카도', url: 'https://www.subway.co.kr/images/menu/img_recipe_v09.jpg' },
];
